### ISSUE TITLE
Why are script names with colons non-compliant?

### ISSUE THREAD

**Issue by ramsey** [php-pds/composer-script-names#1]
A common convention when creating  commands using symfony/console is the use of colons to create namespaces for commands. These namespaces and sub-namespaces can be queried to list the commands in only that namespace. Since Composer is based on symfony/console, it has this functionality out-of-the-box.

For example, `composer list foo` lists all commands that begin with `foo:`, and `composer list foo:bar` lists all commands with the prefix `foo:bar:`. Denying the ability to name commands using colons means projects cannot organize and subdivide their commands into namespaces, which can be useful for projects with lots of Composer scripts.

Using colons in script names also appears to be a common practice in the JavaScript community, where coding standards checks are usually referred to as “linting,” so one commonly sees a `lint` script along with a `lint:fix` script defined in `package.json`. In some of the projects I work on, all of the linting operations (for PHP, JS, CSS, etc.) are combined in the same `lint` and `lint:fix` scripts, and if we want to run them separately, we might do `lint:js`, `lint:php`, and so on.

**Comment by pmjones** [comment]
The reasoning is here: https://github.com/php-pds/composer-script-names_research#naming-convention

One reviewer out of six shared your opinion; cf. https://github.com/php-pds/composer-script-names_research#private-review

Finally: of the 36521 packages that define non-event scripts, only 47 script names use separators in the first place; of those, 35 used dashes and 12 used colons. That's 3:1 in favor of using dashes. So while the Composer functionality may be *present* it appears to be *used* so infrequently as to be never, at least in packages published on Packagist.

Now, does that mean it should be *denied* as part of the standard? Maybe/maybe-not, but the numbers just aren't there to back up a decision like that.

**Comment by ramsey** [comment]
> but the numbers just aren't there to back up a decision like that.

Maybe there's not enough education around best practices for using Composer scripts. Whenever I showcase it in a talk, many of those I'm speaking to hadn't considered using Composer scripts. 🤷🏻‍♂️
